example.property= I AM DEV


spring.datasource.url=jdbc:postgresql://commerce-db.c6hs2eye02n0.us-east-1.rds.amazonaws.com:5432/commerce_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=commerce
spring.datasource.password=commerce
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true