example.property= I AM DEV


spring.datasource.url=jdbc:postgresql://customer-db.c6hs2eye02n0.us-east-1.rds.amazonaws.com/consumer_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=consumer
spring.datasource.password=consumer
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true