apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pauli\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: customer-service
  name: customer-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: customer-service
