apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\pauli\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: gateway-server
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\pauli\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: gateway-server
    spec:
      containers:
        - env:
            - name: CONFIGSERVER_PORT
              value: "8089"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:8089
          image: 861276091195.dkr.ecr.us-east-1.amazonaws.com/ecommerce/gateway-server
          name: gateway-server
          ports:
            - containerPort: 8072
              protocol: TCP
      restartPolicy: Always