input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_tag => [ "E-Commerce" ]
  }
 }

output {
  elasticsearch {
    hosts => ["http://3.238.94.27:9200"]
  }
}